/*
 * Copyright © 2025 Donald O. Isoe (isoedonald@gmail.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ke.don.core_designsystem.material_theme.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF006B54)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF00FFCC)
val onPrimaryContainerLight = Color(0xFF00725A)
val secondaryLight = Color(0xFF266956)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFAAEDD5)
val onSecondaryContainerLight = Color(0xFF2B6E5A)
val tertiaryLight = Color(0xFF3B6377)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFBFE8FF)
val onTertiaryContainerLight = Color(0xFF41697D)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF2FCF6)
val onBackgroundLight = Color(0xFF151D1A)
val surfaceLight = Color(0xFFF2FCF6)
val onSurfaceLight = Color(0xFF151D1A)
val surfaceVariantLight = Color(0xFFD5E7DE)
val onSurfaceVariantLight = Color(0xFF3A4A44)
val outlineLight = Color(0xFF6A7B73)
val outlineVariantLight = Color(0xFFB9CBC2)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF29322F)
val inverseOnSurfaceLight = Color(0xFFE9F3ED)
val inversePrimaryLight = Color(0xFF00E0B3)
val surfaceDimLight = Color(0xFFD2DCD6)
val surfaceBrightLight = Color(0xFFF2FCF6)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFECF6F0)
val surfaceContainerLight = Color(0xFFE6F0EA)
val surfaceContainerHighLight = Color(0xFFE1EBE4)
val surfaceContainerHighestLight = Color(0xFFDBE5DF)

val primaryLightMediumContrast = Color(0xFF003E30)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF007C62)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF003E30)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF377864)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF0C3B4D)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF4B7286)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF2FCF6)
val onBackgroundLightMediumContrast = Color(0xFF151D1A)
val surfaceLightMediumContrast = Color(0xFFF2FCF6)
val onSurfaceLightMediumContrast = Color(0xFF0A1310)
val surfaceVariantLightMediumContrast = Color(0xFFD5E7DE)
val onSurfaceVariantLightMediumContrast = Color(0xFF2A3933)
val outlineLightMediumContrast = Color(0xFF46564F)
val outlineVariantLightMediumContrast = Color(0xFF60716A)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF29322F)
val inverseOnSurfaceLightMediumContrast = Color(0xFFE9F3ED)
val inversePrimaryLightMediumContrast = Color(0xFF00E0B3)
val surfaceDimLightMediumContrast = Color(0xFFBFC9C3)
val surfaceBrightLightMediumContrast = Color(0xFFF2FCF6)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFECF6F0)
val surfaceContainerLightMediumContrast = Color(0xFFE1EBE4)
val surfaceContainerHighLightMediumContrast = Color(0xFFD5DFD9)
val surfaceContainerHighestLightMediumContrast = Color(0xFFCAD4CE)

val primaryLightHighContrast = Color(0xFF003327)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF005441)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF003327)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF055341)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF003041)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF254E61)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF2FCF6)
val onBackgroundLightHighContrast = Color(0xFF151D1A)
val surfaceLightHighContrast = Color(0xFFF2FCF6)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFD5E7DE)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF202F2A)
val outlineVariantLightHighContrast = Color(0xFF3C4D46)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF29322F)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFF00E0B3)
val surfaceDimLightHighContrast = Color(0xFFB1BBB5)
val surfaceBrightLightHighContrast = Color(0xFFF2FCF6)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFE9F3ED)
val surfaceContainerLightHighContrast = Color(0xFFDBE5DF)
val surfaceContainerHighLightHighContrast = Color(0xFFCDD7D1)
val surfaceContainerHighestLightHighContrast = Color(0xFFBFC9C3)

val primaryDark = Color(0xFFFDFFFC)
val onPrimaryDark = Color(0xFF00382B)
val primaryContainerDark = Color(0xFF00FFCC)
val onPrimaryContainerDark = Color(0xFF00725A)
val secondaryDark = Color(0xFF91D4BC)
val onSecondaryDark = Color(0xFF00382B)
val secondaryContainerDark = Color(0xFF00513F)
val onSecondaryContainerDark = Color(0xFF80C2AB)
val tertiaryDark = Color(0xFFFFFEFF)
val onTertiaryDark = Color(0xFF033547)
val tertiaryContainerDark = Color(0xFFBFE8FF)
val onTertiaryContainerDark = Color(0xFF41697D)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0C1512)
val onBackgroundDark = Color(0xFFDBE5DF)
val surfaceDark = Color(0xFF0C1512)
val onSurfaceDark = Color(0xFFDBE5DF)
val surfaceVariantDark = Color(0xFF3A4A44)
val onSurfaceVariantDark = Color(0xFFB9CBC2)
val outlineDark = Color(0xFF83958D)
val outlineVariantDark = Color(0xFF3A4A44)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDBE5DF)
val inverseOnSurfaceDark = Color(0xFF29322F)
val inversePrimaryDark = Color(0xFF006B54)
val surfaceDimDark = Color(0xFF0C1512)
val surfaceBrightDark = Color(0xFF323B37)
val surfaceContainerLowestDark = Color(0xFF07100D)
val surfaceContainerLowDark = Color(0xFF151D1A)
val surfaceContainerDark = Color(0xFF19211E)
val surfaceContainerHighDark = Color(0xFF232C28)
val surfaceContainerHighestDark = Color(0xFF2E3733)

val primaryDarkMediumContrast = Color(0xFFFDFFFC)
val onPrimaryDarkMediumContrast = Color(0xFF00382B)
val primaryContainerDarkMediumContrast = Color(0xFF00FFCC)
val onPrimaryContainerDarkMediumContrast = Color(0xFF005240)
val secondaryDarkMediumContrast = Color(0xFFA7EAD1)
val onSecondaryDarkMediumContrast = Color(0xFF002C21)
val secondaryContainerDarkMediumContrast = Color(0xFF5C9D87)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFFFFEFF)
val onTertiaryDarkMediumContrast = Color(0xFF033547)
val tertiaryContainerDarkMediumContrast = Color(0xFFBFE8FF)
val onTertiaryContainerDarkMediumContrast = Color(0xFF234C5F)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF0C1512)
val onBackgroundDarkMediumContrast = Color(0xFFDBE5DF)
val surfaceDarkMediumContrast = Color(0xFF0C1512)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF3A4A44)
val onSurfaceVariantDarkMediumContrast = Color(0xFFCEE0D8)
val outlineDarkMediumContrast = Color(0xFFA4B6AE)
val outlineVariantDarkMediumContrast = Color(0xFF83948C)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFDBE5DF)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF232C28)
val inversePrimaryDarkMediumContrast = Color(0xFF005240)
val surfaceDimDarkMediumContrast = Color(0xFF0C1512)
val surfaceBrightDarkMediumContrast = Color(0xFF3D4742)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF030906)
val surfaceContainerLowDarkMediumContrast = Color(0xFF161F1C)
val surfaceContainerDarkMediumContrast = Color(0xFF212A26)
val surfaceContainerHighDarkMediumContrast = Color(0xFF2B3531)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF36403C)

val primaryDarkHighContrast = Color(0xFFFDFFFC)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF00FFCC)
val onPrimaryContainerDarkHighContrast = Color(0xFF003024)
val secondaryDarkHighContrast = Color(0xFFBAFEE5)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFF8DD0B8)
val onSecondaryContainerDarkHighContrast = Color(0xFF000E09)
val tertiaryDarkHighContrast = Color(0xFFFFFEFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFBFE8FF)
val onTertiaryContainerDarkHighContrast = Color(0xFF002E3E)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF0C1512)
val onBackgroundDarkHighContrast = Color(0xFFDBE5DF)
val surfaceDarkHighContrast = Color(0xFF0C1512)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF3A4A44)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFE2F4EB)
val outlineVariantDarkHighContrast = Color(0xFFB5C7BE)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFDBE5DF)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF005240)
val surfaceDimDarkHighContrast = Color(0xFF0C1512)
val surfaceBrightDarkHighContrast = Color(0xFF49524E)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF19211E)
val surfaceContainerDarkHighContrast = Color(0xFF29322F)
val surfaceContainerHighDarkHighContrast = Color(0xFF343D39)
val surfaceContainerHighestDarkHighContrast = Color(0xFF3F4945)
